version: 0.0
os: linux
files:
  - source: server/appspec.yml
    destination: /home/ubuntu/action/server/appspec.yml
    overwrite: yes

permissions:
  - object: /home/ubuntu/action/server/appspec.yml
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: server/scripts/deploy.sh
      timeout: 60
      runas: ubuntu