version: 0.0
os: linux
files:
  - source: /path/to/appspec.yml
    destination: /destination/path/appspec.yml
    overwrite: yes

permissions:
  - object: /destination/path/appspec.yml
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: server/scripts/deploy.sh
      timeout: 60
      runas: ubuntu